name: Random
version: 1.1
main: fr.Jivaa.Random.Random
depend: [PluginsBaker]
author: Jivaa_
authors: [Jivaa_]
commands:
  random:
    description: Tire un nombre aléatoire entre min (inclus) et max (inclus). Les bornes sont réglables et faculatifs (min = 1, max = 100).
  rand:
    description: Alias de /random
  alea:
    description: Alias de /random